<?php include("blocks/head.php"); ?>

    <title>ABOUT | ECOFI</title>
    <meta name="description" content="ECO">
</head>
<style type="text/css">
    h1 {
        color:white;
        margin: 0 0 2em;
        font-size: 35px;
        font-family: Electrolize; }
    h3 {
        color:green;
        margin: 0 0 1em;
        font-size: 25px; }
</style>
<body class="whitepaper">

<?php include("blocks/header.php"); ?>
<?php include("blocks/nav-mobile.php"); ?>
        
        <section class="content">
        	<div class="grid center">
<h1>Capturing Value with EcoFi, The Staking Economy</h1>

<h3>Executive Summary</h3>

<p class="left">Cryptocurrency and digital assets represent the evolution of how we assign, perceive, and generate value as a civilization. Those involved in the EcoFi community see the building evidence of this fact every day. The rise of decentralized finance, or DeFi, platforms are the next step in this evolution, opening up an ecosystem comprising automated liquidity markets that are surging.</p> 

<p class="left">The ability to be able to share capital, not in a fractional reserve sense, is unique to DeFi. In 2020 alone, DeFi markets accounted for 95% of $270 billion USD of growth in the Ethereum network. With these attributes, DeFi is already attracting the attention of hedge funds and mainstays of the financial services sector. </p>

<p class="left">During this time of accelerated growth, first movers who act before these large financial institutions acquire a foothold in the DeFi marketplace have an extraordinary opportunity that many, as of yet, have yet to realize. EcoFi’s mission is to help spread awareness and facilitate the greater public to both realize the potential of, and capitalize on this burgeoning marketplace. </p>

<h3>Introduction</h3>
<p class="left">EcoFi is an open-source, permissionless, and censorship-resistant protocol, built to power safe and responsible innovation. We believe in universally accessible financial markets in which financial regulators and community members are aligned. The transformational potential of DeFi to the entire ECOsystem is inevitable, provided that regional laws and regulations protecting consumers are respected.</p>

<p class="left">Although the growth of the world economy has provided an exorbitant amount of value to be captured by the wealthiest individuals in the most privileged positions, the average consumer is unable to utilize the same mechanisms that drive wealth. EcoFi is creating an economy that hinges on driving value directly to the global community via a mechanism system that supports the distribution of interest generated by decentralized mechanisms to community stakeholders that participate in the platform/economy.</p>

<p class="left">The EcoFi platform offers a combination of interest generation via staking, and NFT rewards. The platform will include a compound interest generating mechanism. With the EcoFi model, participants will be able to stake their ECO tokens to the ECOVAULT and earn passive rewards from built-in inflationary and deflationary control mechanisms.</p>


<p class="left">We believe that this mechanism will serve as a model for global income distribution networks, as well as other financial and monetary systems so that areas of the world where extreme poverty is the status quo may adopt and implement it to achieve a higher standard of living.</p>

<h3>Problem statement</h3>
<p class="left">Although banking services profit from the majority of consumers worldwide, the average individual doesn’t meet the criteria to gain access to the exclusive types of financial instruments capable of yielding high returns on an investment.</p>
 
<p class="left">Individuals who do have the capital needed to gain access to these exclusive financial instruments still face the problem that, in order to get incredibly high returns, they must place their capital at incredibly high risk.</p>

<p class="left">By locking value in a cycle that benefits only those who have accumulated enough wealth to take advantage of the system, and simultaneously gatekeeping this system through a network of complicit banking service providers, any newcomer who attempts to gain a fair competitive advantage in the financial marketplace is essentially disenfranchised. This dynamic feeds over into other avenues of life, as money is power, and can often be used to sway political results, lobby legislators, and privatize otherwise public resources for predatory profiteering practices.</p>

<h3>High-level solution</h3>
<p class="left">At EcoFi, we discovered that, with the combination of blockchain and an overhaul of the mechanisms by which assets generate returns, we can create smart contracts to use an asset to indefinitely generate high returns at LOW RISK.</p>

<p class="left">In addition EcoFi takes the concept of NFTs and expands it to encompass actual fractional ownership over the physical art to which the NFT is associated.</p>

<p class="left">These mechanisms are immutable, and unlike the traditional financial world, they cannot be changed at the whim of a centralized, corruptible financial authority. </p>

<h3>Solution</h3>

<h3>Tokenomics Mechanism</h3>
<p class="left">EcoFi’s unique staking model is built to facilitate high returns without the risk generally associated with financial instruments that provide compound interest. To receive these rewards, users must stake ECO tokens. </p>


<h3>Earning Rewards With ECO</h3>
<p class="left">First a user must decide how long to stake their ECO tokens. 50 ECO is the minimum amount of tokens a user must commit to staking and the minimum amount of time to stake ECO tokens is 3 months. If a user decides to unstake their tokens before the three month time period is up, they will forfeit 15% of their total interest, a portion of which will be returned to the Regen Pool.
Once staked ECO tokens earn interest every hour in the form of SPRT tokens that are distributed once daily. Every day 90% of each participant’s total SPRT rewards from staking are deposited into your NFT wallet. The remaining 10% of everyone’s collective SPRT rewards are split in half, where 5% goes into the Regen Pool to earn compound interest. The remaining 5% goes back into the ECOFI MULTISIG contract to go towards the ongoing maintenance of the platform.</p>

<h3>Farming NFTs With SPRT Tokens</h3>
<p class="left">Every day users have a choice to either withdraw their SPRT rewards or keep the SPRT tokens they have earned in the vault to continue generating compounding rewards. The SPRT tokens in the vault can also be used to generate NFTs. When generating an NFT with SPRT tokens, the NFT is deposited into an address of the user’s choice, while the SPRT is burned. The EcoFi team is working to integrate features that support atomic swaps for SPRT and different crypto assets in the future.<br>
“An Endlessly Finite Supply”</p>

<p class="left">SPRT has an endlessly finite supply because every time someone stakes ECO they will be creating SPRT. But every time SPRT is used to generate NFTs or, in the future, is swapped to another crypto asset, the SPRT is burned in the process. Burning SPRT at every economic gateway safeguards against the type of excess that ultimately drives down value, effectively eliminating recirculation. This gives the staking platform the capacity to scale upward or downwards based on demand.</p>
<p class="left">EcoFi is an open-source decentralized technology platform, built to facilitate the growth and evolution of the DeFi marketplace on the Ethereum blockchain. EcoFi’s unique and innovative use of NFT assets, physical, and digital rewards, as well as liquidity pairs and yield farming will help to transform the future of the financial ECOsystem.</p>

<h3>Personal benefits</h3>
<p class="left">The EcoFi staking economy is designed to drive rewards directly into the community. For every 1 ECO staked a user will earn an average of 1035 SPRT from the minimum 3 month staking period.</p>

<p class="left">SPRT will be used to generate rare NFTs, available in the EcoFi marketplace. EcoFi is strategically partnering with major platforms, artists, and professionals across a wide array of mediums to create the finest quality NFTs, tied to actual physical ownership of an art piece. In the future we intend to expand the SPRT marketplace to encompass anything that can be tokenized, to create a truly decentralized bazaar of goods ranging from fine art, to anything else you can possibly imagine.</p>

<h3>Hyper Object</h3>
<p class="left">EcoFi has entered into a dynamic partnership with HyperObject, a Los Angeles based art collective to create its first DeFi NFT marketplace enabled by SPRT. This partnership enables the community to become shareholders in real-world fine art pieces. </p>

<p class="left">Hyper Object is a crypto-gallery space founded in 2021 by Ecofi and SOVO// Projects. The Hyper Object crypto-gallery stands at the forefront of the NFT revolution, representing a collision of technology and art. This new art gallery for digital assets provides affordable access to authenticated, limited edition NFTs for entry to mid- level collectors and is the only gallery with financial investment and asset management support woven into its DNA. </p>

<p class="left">ECOFI has partnered with SOVO// Projects to bring this ambitious initiative to life. HYPEROBJECT will serve as a virtual digital platform,  welcoming art collectors in the crypto space, and  around the world. Users can obtain a platform membership for as little as $50, which is converted into Sprout (SPRT) tokens. Hold SPRT while it appreciates and builds capital while investing in the artwork sold in the HYPEROBJECT ecosystem.  HYPEROBJECT offers a variety of additional membership tiers, ranging from $50 to upwards of $250,000 for investors to take advantage of and become first movers in this dynamic digital asset marketplace.</p>
 

<h3>Community benefits</h3>
<p class="left">To avoid rampant inflation, EcoFi’s economic model must be finely tuned. In order to implement a compound inflation structure that is robust against hyper-inflation, we are consulting with expert economics. We will provide additional updates as we continue to test, develop, and integrate this feature on the live platform.</p>

<h3>Tokenecomics</h3>
<p class="left">Of the ECO token supply that hasn’t been acquired by the EcoFi community the remaining tokens will be allocated as follows by the team:<br><br>
10% of the supply will be kept for platform development<br>
10% will go to private equity investment<br>
~40% will go community offerings<br>
15% will go to marketing<br>
5% will go to overhead and support</p>


<h3>DAO Governance</h3>
<h3>EcoFi’s Commitment To Decentralized Autonomous Governance</h3>
<p class="left">In the relatively short period of time it has taken for liquidity providers to capitalize on yield farming, projects have come and gone which have manifested little to no actual value for the ecosystem.</p>

<p class="left">EcoFi is committed to the long-term perseverance of the staking ECOnomy, as well as the belief that the community has a right to play a self determining role in the growth and evolution of the platform. That is why the EcoFi founders have chosen to ultimately burn the administrator tokens and turn the platform over to an Autonomous Decentralized Organization mode of governance.</p>

<p class="left">Before this change in governance can take place, the EcoFi founders plan to guide stable the growth of the EcoFi ecosystem by deploying platform features including staking, yield farming, and our exclusive NFT marketplace. Our goal is to turn over a reliable, stable, bug-free platform for the community to vote and steer the project’s evolution.</p>

<p class="left">EcoFi’s transition to DAO based governance will preserve the long-term trajectory of the project and eliminate the risks associated with centrally controlled project funding which may result in conflicts of interest, flawed incentives, and can be hazardous to the fund’s health as it grows.</p>

<h3>Community Strategies and Voting</h3>
<p class="left">The voting mechanism for the DAO governance model is still in the engineering phase. Our goal is to provide EcoFi token holders a means to provide feedback on strategy, contracts, and documentation. Subsequently, once a voting system is integrated, community votes determine what is launched and when to decentralize autonomous strategy execution.</p>

<h3>Roadmap</h3>
<p class="left">These are the approximate milestones the EcoFi team will accomplish in the forthcoming year. Some projects may be completed ahead of the approximated timeline.</p>

<h3>2020 Q4</h3>
<p class="left">EcoFi project launch</p>

<h3>2021 Q1</h3>
<p class="left">Seed Investment Round Closes<br>
SPRT Generation Mechanism Development, Auditing, and Beta<br>
HyperObject NFT Collaboration Announcement<br>
HyperObject Gallery Goes Live</p>

<h3>2021 Q2</h3>
<p class="left">Staking Mechanism Development, Auditing, and Implementation<br>
SPRT Generation Mechanism Live<br>
HyperObject NFT Marketplace goes live</p>

<h3>2021 Q3</h3>
<p class="left">Public NFT Marketplace Development, Auditing, Beta, and Launch</p>

<h3>2021 Q4</h3>
<p class="left">Public Marketplace Moderation Effort<br>
DAO Governance Voting Mechanism Development, Auditing, and Beta<br>
DAO Governance Implementation</p>


<h3>Conclusion</h3>
<p class="left">As we continue to build EcoFi into the leading open-source, permissionless, and censorship resistant protocol, we are making an effort to adhere to best practices and create a safe and responsible DeFi space.</p>

<p class="left">Our immediate focus will be to continue rewarding ECO holders and community participants, as we develop, audit, and stress test the platform’s compound interest generating smart contract mechanism. We hope that this mechanism may some day serve as the basis for value distribution systems in areas of the world where extreme poverty is status quo.</p>

<p class="left">We believe that the ability to be able to share capital outside the confines of fractional reserve infrastructures is unique to DeFi. This year we intend to focus on community building, capital efficiency, and yields within the ECOsystem.</p>

<h3>Want to learn more about EcoFi? </h3>
<p class="left">Become an early adopter and participate in the official ECO coin offering, and read the Lit Paper at #. Remember to avoid scams; EcoFi.io is the only place to get ECO tokens.</p>

<h3>Get Involved</h3>
<p class="left">We are beginning to design the architecture of a functional DAO, taking lessons from the successes and mistakes of our predecessors. We invite members of the community to participate in this process as we help to create a platform for everyone and DeFined by a cooperative community. Join the conversation in our official telegram channel at: <a href="https://t.me/joinchat/Ruaf6hmBWozjFP40-qJrvA">@EcoFi</a></p>
            </div>

        </section>

<?php include("blocks/footer.php"); ?>

<script type="text/javascript" src="scripts.js"></script>

</body>
</html>